# -*- coding: utf-8 -*-
"""ATR and  Bollinger band.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cc98SUfnqUyhftc3dlCShGakz9LDoQbv
"""

pip install yfinance

import yfinance as yf 
import pandas as pd
import datetime as dt

## to calculate ATR (average true range )

tickers=["TCS.NS","INFY.NS","PIDILITIND.NS","NAUKRI.NS","ASIANPAINT.NS","ABCAPITAL.NS","PIIND.NS","MINDACORP.NS","BAJAJFINSV.NS","BORORENEW.NS","ESCORTS.NS"] ## for getting data of multiple stocks 
ohlcv_data={}

for ticker in tickers:
    temp=yf.download(ticker,period="1mo",interval="5m")   ## to get data  of selected stocks for 1 months  at a interval of 15 minute
    temp.dropna(how="any",inplace=True)
    ohlcv_data[ticker]=temp
def ATR(DF,n=14):
    df=DF.copy()
    df["H-L"]=df["High"]-df["Low"]
    df["H-PC"]=df["High"]-df["Adj Close"].shift(1)
    df["L-PC"]=df["Low"]-df["Adj Close"].shift(1)
    df["TR"]=df[["H-L","H-PC","L-PC"]].max(axis=1,skipna=False)
    df["ATR"]=df["TR"].ewm(span=n,min_periods=n).mean()
    return df["ATR"]
for ticker in ohlcv_data:
    ohlcv_data[ticker]["ATR"]=ATR(ohlcv_data[ticker])

ohlcv_data

ohlcv_data["TCS.NS"]

# to calculate bollinger band

tickers=["TCS.NS","INFY.NS","PIDILITIND.NS","NAUKRI.NS","ASIANPAINT.NS","ABCAPITAL.NS","PIIND.NS","MINDACORP.NS","BAJAJFINSV.NS","BORORENEW.NS","ESCORTS.NS"] ## for getting data of multiple stocks 
ohlcv_data={}

for ticker in tickers:
    temp=yf.download(ticker,period="1mo",interval="5m")   ## to get data  of selected stocks for 1 months  at a interval of 5 minute
    temp.dropna(how="any",inplace=True)
    ohlcv_data[ticker]=temp
def Boll_Band(DF,n=14):
    df=DF.copy()
    df["MB"]=df["Adj Close"].rolling(n).mean()
    df["UB"]=df["MB"]+2*df["Adj Close"].rolling(n).std(ddof=0)
    df["LB"]=df["MB"]-2*df["Adj Close"].rolling(n).std(ddof=0)
    df["BB_Width"]=df["UB"]-df["LB"]
    return df[["MB","UB","LB","BB_Width"]]
for ticker in ohlcv_data:
    ohlcv_data[ticker][["MB","UB","LB","BB_Width"]]=Boll_Band(ohlcv_data[ticker],20)

ohlcv_data